### ISSUE TITLE
How to know this action is Security

### ISSUE THREAD

**Issue by fpt-phongnx8** [marocchino/sticky-pull-request-comment#1035]
Hi team,

I would like to use this action for my project workflow but I don't know is It security.
Please how to know about this

**Comment by marocchino** [comment]
I don't think any action can guarantee that. If you are concerned about security, please review a specific version and use a fixed version that has been checked. Fortunately, this repo is very small.

**Comment by fpt-phongnx8** [comment]
Thank you,
I use like this

  - name: Hide the previous comment and add a comment at the end
    uses: marocchino/sticky-pull-request-comment@f6a2580ed520ae15da6076e7410b088d1c5dddd9 #v2.7.0
    with:
      hide_and_recreate: true
      hide_classify: "OUTDATED"
      path: comment.md
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

Thank for your repository, It's good for me.

**Comment by fpt-phongnx8** [comment]
I will close this issue
