### ISSUE TITLE
Admin privilages are required

### ISSUE THREAD

**Issue by nbolton** [marocchino/sticky-pull-request-comment#1397]
I created a PAT with `discussion:write` permissions, but then I got an error:

![image](https://github.com/user-attachments/assets/048faa04-7ebe-4c54-8c12-9709dce4d337)

I was wary of creating a PAT for writing comments, but I'm certain that creating a PAT with admin is a bad idea.

Why is it that this action requires admin privs?

**Comment by marocchino** [comment]
discussion:write is about discussion menu. maybe you need `contents:write`.
[Contents"](https://docs.github.com/en/rest/authentication/permissions-required-for-github-apps?apiVersion=2022-11-28#repository-permissions-for-contents)
