### ISSUE TITLE
Delete old comment

### ISSUE THREAD

**Issue by Blisto91** [marocchino/sticky-pull-request-comment#160]
Would it be possible to add an option to delete the previous action comment?

Instead of adding a extra comment every time a workflow has run or only updating an old one i would like to be able the delete the previous one before posting so there is only one at the bottom.

**Comment by marocchino** [comment]
Maybe recreate option will do that. see: #138

**Comment by Blisto91** [comment]
Oh yea hadn't noticed that.
Will try it out :)

**Comment by marocchino** [comment]
closed by #187
