### ISSUE TITLE
This would probably benefit from a brief example of what this would look like from a user perspective.

### ISSUE THREAD

**Issue by StingyJack** [marocchino/sticky-pull-request-comment#219]
Like what are some of the ways this would be typically used?

**Comment by marocchino** [comment]
Hi, @StingyJack. 
The definition of 'typically' is difficult for me. There are many combinations possible, and writing down all of them seems to be lengthy.
Let's do this. Ask if what you want is possible. When that becomes a normal case, I will put it in the readme.

**Comment by StingyJack** [comment]
Hi, 
I was looking for an example so that I could tell what this is. I found it when I was looking up some problem I was having with the GH Issue API, and I am not sure if its something that would be useful to me or not.

**Comment by marocchino** [comment]
Hi. Thank you for answer. But I can't find any ideas to shape your needs yet. I'll close this issue for now, but you can always reopen it if you can materialize it in another way. I don't know what you're making, but good luck with it.

**Comment by StingyJack** [comment]
I came across this repo while looking for something, and for the life of me cannot figure out what it does or what it's useful for. 

Like what *is* a sticky pull request comment? What does it look like, how does it help, etc? 

If you don't want to explain the minimum What? and Why? (so that people can become interested and informed), that's your choice.

**Comment by marocchino** [comment]
I took your comment seriously and realized that I had omitted the premise to use this tool. Thank you. 4fd172b4d
