### ISSUE TITLE
Delete will create a new message when no previous comment is found

### ISSUE THREAD

**Issue by oxc** [marocchino/sticky-pull-request-comment#226]
The "delete comment" action example from the documentation does not work, because it requires either a message or a path specified.

Furthermore, it will create that message when no previous comment can be found.

**Comment by oxc** [comment]
Plus, the documentation calls it "delete last commit", when it should be "delete last **comment**".

**Comment by marocchino** [comment]
Thank you for your report. fixed in acc9cee and release as `v2`
