### ISSUE TITLE
"Error: Resource not accessible by integration" for a PR from a fork

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [marocchino/sticky-pull-request-comment#227]
![image](https://user-images.githubusercontent.com/56065213/105687010-39d39500-5ef8-11eb-96d8-1286c2d5befa.png)

An external contributor created a PR and our action tried to comment on it. Unfortunately it failed with the above error message.
I'm guessing this error means that the github token used does not have permission to perform this. This is also indicated here: https://github.com/actions/first-interaction/issues/10

Any idea how to fix this?

**Comment by christian-kreuzberger-dtx** [comment]
After digging a bit deeper, one possible fix is to use [`on: pull_request_target`](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request_target) rather than `on: pull_request`.

Though this means we should not build any code etc... in the same workflow (which we do, in our case). 

For now I'll disable the PR reporter for forks.

**Comment by marocchino** [comment]
The most probable alternative right now is to use crontab or [artifact](https://github.com/yewstack/yew/blob/master/.github/workflows/publish-website.yml).

Crontab is not an immediate response, and it is burdensome to upload files every time. Comments using artifacts will be summarized later and updated in README. I need some testbed for it. I don't know how to get it, but I'll try.
