### ISSUE TITLE
🐛 If the number of comments exceeds 50, it cannot be updated and a new comment is created. 

### ISSUE THREAD

**Issue by marocchino** [marocchino/sticky-pull-request-comment#269]
I can increase it up to 100, but if it exceeds 100, the same problem occurs, so it is not a perfect solution. 

ref list api https://docs.github.com/en/rest/reference/issues#list-issue-comments

**Comment by polarathene** [comment]
I think the correct approach to workaround that should it ever be an issue in practice... is to:
1. Update the existing (old) comment header. Perhaps with prefix/suffix number (eg `--outdated-0`)
2. Add a new comment with expected `header` value if relevant.
3. Reference the old comment for history/tracking (might be useful in future for the action or other purposes).
4. Edit the new comment to continue normal behaviour and apply the actual comment content.
5. Mark the old comment as _outdated_, so it is hidden but retained (can expand it to view).

That should allow for continuing the comment updates non-destructively while allowing for some automation if needed to "follow" old comments. That may require other features of the action to also handle such as delete.

Alternatively a simpler behaviour is to delete and start again if the older history isn't important.

You could offer it as a config option such as `commentChain`/`commentHistory`/`multi-comment` with `true` (retain) or `false` (delete old comments). Documentation just needs to explain the comment edit limitation and what the default behaviour of the action is (eg retain by creating a new comment and hiding the old one as outdated).

---

One other optimization you can do. I think if the message is the same, it still performs an edit even if nothing changed? (might have been another action)

Originally I just provided a deploy preview URL that is always the same for a PR (uses the PR number), that would not need to be updated and would avoid the problem if it was not counted as an edit. Now I also include the commit that triggered it, so it is always different, but I have not had this many edits yet to be a problem :)
