### ISSUE TITLE
Option to not send email notification with comment update

### ISSUE THREAD

**Issue by jaqx0r** [marocchino/sticky-pull-request-comment#286]
I have a very large PR comment update (benchmark results) and I would like to disable email notification when the comment is updated as it's too big an email when scrolling through messages.

**Comment by marocchino** [comment]
Right now the [GitHub API](https://octokit.github.io/rest.js/v18#issues-update-comment) doesn't have a option about the email. 
So there seems to be no way to add features or options to this action. 

Maybe this article will be help.
https://docs.github.com/en/github/managing-subscriptions-and-notifications-on-github/managing-notifications-from-your-inbox#custom-filter-limitations

**Comment by jaqx0r** [comment]
Thankyou.

That is disappointing that you can't opt out a type of comment from
automation.
