### ISSUE TITLE
Can we have it edit the comment in place instead of deleting and recreating?

### ISSUE THREAD

**Issue by tcheinen** [marocchino/sticky-pull-request-comment#386]
I currently am using it on append mode because I want history, but for PRs which get a number of changes that could get really long. Is it possible currently to have it edit the existing comment in place so I can see previous comments via the edit history?

**Comment by marocchino** [comment]
Hi. @tcheinen, Can I see your option? I thought that default behavior.

**Comment by tcheinen** [comment]
It's possible I've just confused myself -- I read the description and saw that it mentioned deleting and recreating it so I just went towards the append option.  Which option should get that behavior?  I'm packing to move back to school rn but I'll play around with it tomorrow

**Comment by marocchino** [comment]
Without `delete` or `recreate` options, It will not delete current comment. If not, please report it. 😅

**Comment by tcheinen** [comment]
Ah I see, github doesn't log changes if the change is identical so I assumed it didn't do anything. Everything looks fine, sorry for bothering you!
