### ISSUE TITLE
Deprecation warning about using Node.js 12

### ISSUE THREAD

**Issue by plankp** [marocchino/sticky-pull-request-comment#770]
Hi, I get the following warning when I used this plugin in my workflow:

> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: marocchino/sticky-pull-request-comment

Would like to know if this action will update to using Node.js 16.

**Comment by ofek** [comment]
We also are seeing this

**Comment by marocchino** [comment]
@plankp Hi, Thank you for report.
I just uploaded the node version and released a new version. Can you please check if the warning is gone?

**Comment by plankp** [comment]
Yes, the warning is gone after using the new version.
Thanks!

**Comment by ofek** [comment]
Thank you!
