### ISSUE TITLE
Node.js 12 actions are depreciated

### ISSUE THREAD

**Issue by mattosaurus** [marocchino/sticky-pull-request-comment#819]
Thanks for creating this action, it's really appreciated.

We've noticed that we've started recieving warnings when running it now as can be seen here.

https://github.com/marocchino/on_artifact/actions/runs/3468589434

`Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout@v2`

I think the checkout action just needs updating here and in your on_artifact repository to v3.

I'm happy to put in a PR for this unless there's a reason you need to keep them at v2.

**Comment by mattosaurus** [comment]
Actually, our warning messages weren't coming from this action after all, though it's probably worth updating the checkout actions anyway.

**Comment by marocchino** [comment]
Thank you for telling me.
I have set up dependabot for github action in both repositories.
