### ISSUE TITLE
Resource not accessible by integration when trying to comment on a PR

### ISSUE THREAD

**Issue by AmeerAssadi** [marocchino/sticky-pull-request-comment#893]
Hi,

I have an actions workflow that comments on a PR request, I've added a token with the necessary permissions but it keeps failing and I got the following error:

```
Error: Request failed due to following response errors:
 - Resource not accessible by integration  
```

**Comment by marocchino** [comment]
Check your Settings > Actions > General > Workflow permissions
<img width="814" alt="Screenshot 2023-02-10 at 2 33 11" src="https://user-images.githubusercontent.com/128431/217892563-da1574f0-baaa-4df2-8095-61650328216b.png">

**Comment by AmeerAssadi** [comment]
@marocchino I already enabled the read/write permissions in `Workflow permissions` the problem not solved.

**Comment by marocchino** [comment]
geuleohdamyeon jega dowajulsu issneunge eobs-eoboibnida. tokeun bellideisyeon-e gwanhan geon gisheobeuui gongsigmunseoleul chamjohasineunge joh-aboibnida. tokeun bellideisyeon-e gwanhan geul-eun inteones-eseo chaj-eul su iss-eul geobnida. gaeinjeog-euloneun tokeun-eul dasi mandeul-eoboneun geos-eul chucheonhabnida.
Show more
130 / 5,000
Translation results
Translation result
If so, I don't see anything I can help with. Regarding token validation, it seems good to refer to the official documentation on GitHub. Articles about token validation can be found on the Internet. Personally, I recommend recreating the token.

**Comment by marocchino** [comment]
If so, I don't see anything I can help with. Regarding token validation, it seems good to refer to the official documentation on GitHub. Articles about token validation can be found on the Internet. Personally, I recommend recreating the token.
