### ISSUE TITLE
Potential missing configuration option

### ISSUE THREAD

**Issue by BioPhoton** [marocchino/sticky-pull-request-comment#898]
# Problem

I have a if else condition to either recreate and hide or just recreate.

It seems I can only use one of those options. 

# Possible solution

The action inputs could be `on` and `off` so we could compose this behavior.

e.g. `delete: 'off'`

**Comment by marocchino** [comment]
You can use `hide_and_recreate` for now. I will rearrange options in the next major.

**Comment by BioPhoton** [comment]
Nice THX!!!

Just to give more context, I cant use the suggested setting because I have to adjust the behavior based on action inputs. I reuse your action and there is no nice way to do if else in a action.

**Comment by BioPhoton** [comment]
Hi @marocchino 

> I will rearrange options in the next major.
Is this already done? i saw activity.
