### ISSUE TITLE
It is possible to add the message inside a collapsible section?

### ISSUE THREAD

**Issue by OtavioCapila** [marocchino/sticky-pull-request-comment#907]
Right now, I'm using the `path` to point to a markdown code coverage test result, but there are a **LOT** of files, it's near to 180 lines.

It's possible to append that file inside a collapsible section? Something like this: 

<details>
  <summary>Click to expand the code coverage report </summary>
   Report here using `path` inside the `message` configuration property
</details>

**Comment by Luc45** [comment]
This repo does it.
Example: https://github.com/marocchino/sticky-pull-request-comment/pull/906#issuecomment-1437536547
Code: https://github.com/marocchino/sticky-pull-request-comment/blob/main/.github/workflows/comment_on_workflow_run.yml

**Comment by OtavioCapila** [comment]
Thank you @Luc45 , I'll try to reproduce this inside my GHA
