### ISSUE TITLE
A workaround for forked repos

### ISSUE THREAD

**Issue by nyurik** [marocchino/sticky-pull-request-comment#99]
Hi, I implemented a workaround for the forked repos. I did it using bash / curl / jq, so it went much faster than a full blown action implementation, but I used your approach for the sticky comment posting. I think you might be interested in either adapting my approach for your action, or possibly create a new one?  See https://github.com/nyurik/auto_pr_comments_from_forks

**Comment by marocchino** [comment]
Hi.
I don't recommend cron approach. Because it uses too many resources. But someone may need it, it would be a good idea to make use cases with appropriate warnings.

Thanks for the suggestion.

**Comment by nyurik** [comment]
@marocchino it depends how often it runs -- technically it uses just a few curl calls, or if the repo is dormant, it would only need 1 curl. The main issue is that if I submit a PR into your repo (or any other FOSS project), there is no way an action could post a comment about my PR, and that's what I tried to solve.
